controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController


arm_controller:
  ros__parameters:
    joints:
      - Revolute_1
      - Revolute_2
      - Revolute_3
      - Revolute_4

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false


gripper_controller:
  ros__parameters:
    joints:
      - Slider_1
    interface_name: position
